In [49]:
%config Completer.use_jedi = False

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): arr2 = my_arr * 2

CPU times: user 10 ms, sys: 11 ms, total: 21 ms
Wall time: 37.2 ms


In [3]:
%time for _ in range(10): arr2 = [i*2 for i in my_list]

CPU times: user 414 ms, sys: 92.5 ms, total: 507 ms
Wall time: 506 ms


In [4]:
data = np.random.randn(2,3)
data

array([[ 0.41528938, -1.60925174,  1.76440947],
       [-0.64879089,  0.15730547, -0.16833125]])

In [5]:
print(data+data)

[[ 0.83057876 -3.21850349  3.52881894]
 [-1.29758177  0.31461094 -0.33666249]]


In [6]:
print(data*10)

[[  4.15289381 -16.09251745  17.64409468]
 [ -6.48790886   1.57305469  -1.68331246]]


In [7]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


# Creating ndarrays

In [8]:
data1 = [6, 5, 3.45, 1.23]
arr1 = np.array(data)
arr1

array([[ 0.41528938, -1.60925174,  1.76440947],
       [-0.64879089,  0.15730547, -0.16833125]])

In [9]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [11]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.empty((2,3,2)) # garbage value may be returned

array([[[4.64695427e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.full((3,3), fill_value=3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

# Data Types for ndarrays

In [18]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int64)

print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [19]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [22]:
float_arr = arr.astype(np.float32)
float_arr.dtype

dtype('float32')

In [23]:
arr = np.array([4.1, 1.2, -1.2])
arr.astype(np.int64)

array([ 4,  1, -1])

In [24]:
numeric_strings = np.array(['1.2', '-3.45', '5.67'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.2 , -3.45,  5.67])

In [25]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Arithmetic with NumPy Arrays

In [26]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [28]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
arr2 = np.array([[0.,4.,7.],[4.,5.,6.]])

print(arr)
print(arr2)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 4. 7.]
 [4. 5. 6.]]


In [33]:
arr2 > arr

array([[False,  True,  True],
       [False, False, False]])

# Basic Indexing and Slicing

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5:8]

array([5, 6, 7])

In [38]:
arr[5:8] = 99
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9])

In [39]:
arr_slice = arr[5:8]
arr_slice

array([99, 99, 99])

In [40]:
arr_slice[1] = 123456789

In [42]:
arr

array([        0,         1,         2,         3,         4,        99,
       123456789,        99,         8,         9])

In [43]:
arr_slice[:] = 10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [44]:
# for copying
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [45]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [46]:
print(arr2d[0][2])
print(arr2d[0, 2])

3
3


In [47]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[1, 0]

array([7, 8, 9])

Note that in all of these cases where subsections of the array have been selected, the
returned arrays are views.

In [54]:
arr[1:6]

array([ 1,  2,  3,  4, 10])

In [56]:
# select the first two rows of arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [58]:
arr2d[1, :2]

array([4, 5])

In [62]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [63]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [67]:
arr2d[2]
arr2d[2, :]
arr2d[2:, :]

array([[7, 8, 9]])

# Boolean Indexing

In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [70]:
data = np.random.randn(7, 4)

In [71]:
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.68023307  0.7066458   0.77869474 -0.15376244]
 [-0.72201913 -0.52564411  0.3208862   0.08138547]
 [ 0.40523971 -0.09011214 -0.07468547 -1.38285079]
 [-0.79054472 -0.77457234  2.2004927   1.28184392]
 [ 0.15355489  0.49668567  1.04858594  1.24312231]
 [-0.1126866  -1.99317427  0.00753905  0.32685984]
 [-0.73903102  0.11513945 -0.1785682  -0.26795707]]


In [72]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [73]:
data[names == "Bob"]

array([[ 0.68023307,  0.7066458 ,  0.77869474, -0.15376244],
       [-0.79054472, -0.77457234,  2.2004927 ,  1.28184392]])

In [74]:
data[names == "Bob", 2:]

array([[ 0.77869474, -0.15376244],
       [ 2.2004927 ,  1.28184392]])

In [76]:
data[names == "Bob", 3:]

array([[-0.15376244],
       [ 1.28184392]])

In [77]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [78]:
data[~(names == "Bob")]

array([[-0.72201913, -0.52564411,  0.3208862 ,  0.08138547],
       [ 0.40523971, -0.09011214, -0.07468547, -1.38285079],
       [ 0.15355489,  0.49668567,  1.04858594,  1.24312231],
       [-0.1126866 , -1.99317427,  0.00753905,  0.32685984],
       [-0.73903102,  0.11513945, -0.1785682 , -0.26795707]])

In [79]:
cond = names == "Bob"
data[~cond]

array([[-0.72201913, -0.52564411,  0.3208862 ,  0.08138547],
       [ 0.40523971, -0.09011214, -0.07468547, -1.38285079],
       [ 0.15355489,  0.49668567,  1.04858594,  1.24312231],
       [-0.1126866 , -1.99317427,  0.00753905,  0.32685984],
       [-0.73903102,  0.11513945, -0.1785682 , -0.26795707]])

In [80]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [81]:
data[mask]

array([[ 0.68023307,  0.7066458 ,  0.77869474, -0.15376244],
       [ 0.40523971, -0.09011214, -0.07468547, -1.38285079],
       [-0.79054472, -0.77457234,  2.2004927 ,  1.28184392],
       [ 0.15355489,  0.49668567,  1.04858594,  1.24312231]])

In [83]:
data[data < 0] = 0
data

array([[0.68023307, 0.7066458 , 0.77869474, 0.        ],
       [0.        , 0.        , 0.3208862 , 0.08138547],
       [0.40523971, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.2004927 , 1.28184392],
       [0.15355489, 0.49668567, 1.04858594, 1.24312231],
       [0.        , 0.        , 0.00753905, 0.32685984],
       [0.        , 0.11513945, 0.        , 0.        ]])

# Fancy Indexing

In [86]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [87]:
arr[[0,2,4,6]]

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [88]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [89]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [94]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [95]:
arr[[1,5,7,2]][:, [3,2,1,0]]

array([[ 7,  6,  5,  4],
       [23, 22, 21, 20],
       [31, 30, 29, 28],
       [11, 10,  9,  8]])

Keep in mind that fancy indexing, unlike slicing, always copies the data into a new
array.

# Transposing Arrays and Swapping Axes